/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * AlisverisSepeti.API
 * OpenAPI spec version: 1.0
 */
export interface Advertisement {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  productUrl?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  email?: boolean;
}

export interface AuthResponseDto {
  requiresOtp?: boolean;
  /** @nullable */
  email?: string | null;
}

export interface AuthResponseDtoResult {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  data?: AuthResponseDto;
}

export interface CollaboratorResponseDto {
  id?: number;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  inviteeId?: number | null;
  /** @nullable */
  inviteeEmail?: string | null;
  /** @nullable */
  inviteeName?: string | null;
  /** @nullable */
  profilePictureUrl?: string | null;
}

export interface CollaboratorResponseDtoIEnumerableResult {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: CollaboratorResponseDto[] | null;
}

export interface ForgotPasswordDto {
  /** @nullable */
  email?: string | null;
}

export interface InviteDto {
  listId?: number;
  /** @nullable */
  inviteeEmail?: string | null;
  /** @nullable */
  role?: string | null;
}

export interface InviteResponseDto {
  id?: number;
}

export interface InviteResponseDtoResult {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  data?: InviteResponseDto;
}

export interface LoginDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface MyInvitesResponseDto {
  id?: number;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  listTitle?: string | null;
  /** @nullable */
  inviterName?: string | null;
  /** @nullable */
  inviterEmail?: string | null;
  /** @nullable */
  profilePictureUrl?: string | null;
}

export interface MyInvitesResponseDtoIEnumerableResult {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: MyInvitesResponseDto[] | null;
}

export interface Role {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  name?: string | null;
}

export interface User {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  hashedPassword?: string | null;
  /** @nullable */
  passwordSalt?: string | null;
  /** @nullable */
  shoppingLists?: ShoppingList[] | null;
  /** @nullable */
  profilePictureUrl?: string | null;
  roleId?: number;
  role?: Role;
}

export interface ShoppingList {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  tag?: string | null;
  isShared?: boolean;
  userId?: number;
  user?: User;
  /** @nullable */
  shoppingListItems?: ShoppingListItem[] | null;
  /** @nullable */
  currentUserRole?: string | null;
  isDraft?: boolean;
}

export interface ShoppingListItem {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  listId?: number;
  productId?: number;
  quantity?: number;
  isChecked?: boolean;
  shoppingList?: ShoppingList;
  product?: Product;
}

export interface Product {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  productName?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  shoppingListItems?: ShoppingListItem[] | null;
}

export interface RegisterDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface RegisterResponseDto {
  userId?: number;
}

export interface RegisterResponseDtoResult {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  data?: RegisterResponseDto;
}

export interface ResendOtpDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  operation?: string | null;
}

export interface ResetPasswordDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  otp?: string | null;
  /** @nullable */
  newPassword?: string | null;
}

export interface Result {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
}

export interface ShoppingListIEnumerableResult {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: ShoppingList[] | null;
}

export interface ShoppingListResult {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  data?: ShoppingList;
}

export interface TokenResponseDto {
  /** @nullable */
  token?: string | null;
  expiration?: string;
  userId?: number;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  profilePictureUrl?: string | null;
  /** @nullable */
  role?: string | null;
}

export interface TokenResponseDtoResult {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  data?: TokenResponseDto;
}

export interface VerifyOtpDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  otp?: string | null;
}

export type PostApiUsersUploadProfilePictureBody = {
  file?: Blob;
};

