/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * AlisverisSepeti.API
 * OpenAPI spec version: 1.0
 */
export interface Advertisement {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  productUrl?: string | null;
  /** @nullable */
  imageUrl?: string | null;
}

export interface InviteDto {
  listId?: number;
  /** @nullable */
  inviteeEmail?: string | null;
  /** @nullable */
  role?: string | null;
}

export interface LoginDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface Role {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  name?: string | null;
}

export interface User {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  hashedPassword?: string | null;
  /** @nullable */
  passwordSalt?: string | null;
  /** @nullable */
  shoppingLists?: ShoppingList[] | null;
  /** @nullable */
  profilePictureUrl?: string | null;
  roleId?: number;
  role?: Role;
}

export interface ShoppingList {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  tag?: string | null;
  isShared?: boolean;
  userId?: number;
  user?: User;
  /** @nullable */
  shoppingListItems?: ShoppingListItem[] | null;
  /** @nullable */
  currentUserRole?: string | null;
  isDraft?: boolean;
}

export interface ShoppingListItem {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  listId?: number;
  productId?: number;
  quantity?: number;
  isChecked?: boolean;
  shoppingList?: ShoppingList;
  product?: Product;
}

export interface Product {
  id?: number;
  createdDate?: string;
  /** @nullable */
  updatedDate?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  productName?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  shoppingListItems?: ShoppingListItem[] | null;
}

export interface RegisterDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export type GetDraftsParams = {
id?: number;
};

export type PostApiUsersUploadProfilePictureBody = {
  file?: Blob;
};

