/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * AlisverisSepeti.API
 * OpenAPI spec version: 1.0
 */
export interface ListShare {
  id?: number;
  userId?: number;
  listId?: number;
  /** @nullable */
  role?: string | null;
}

export interface LoginDto {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface User {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  hashedPassword?: string | null;
  /** @nullable */
  passwordSalt?: string | null;
  /** @nullable */
  shoppingLists?: ShoppingList[] | null;
}

export interface ShoppingList {
  id?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  tag?: string | null;
  isShared?: boolean;
  userId?: number;
  user?: User;
  /** @nullable */
  shoppingListItems?: ShoppingListItem[] | null;
}

export interface ShoppingListItem {
  id?: number;
  listId?: number;
  productId?: number;
  quantity?: number;
  isChecked?: boolean;
  shoppingList?: ShoppingList;
  product?: Product;
}

export interface Product {
  productId?: number;
  /** @nullable */
  productName?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  shoppingListItems?: ShoppingListItem[] | null;
}

export interface RegisterDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}

