/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * AlisverisSepeti.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListShare,
  LoginDto,
  Product,
  RegisterDto,
  ShoppingList,
  ShoppingListItem,
  User
} from './endpoints.schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type postApiAuthRegisterResponse200 = {
  data: void
  status: 200
}

export type postApiAuthRegisterResponseSuccess = (postApiAuthRegisterResponse200) & {
  headers: Headers;
};
;

export type postApiAuthRegisterResponse = (postApiAuthRegisterResponseSuccess)

export const getPostApiAuthRegisterUrl = () => {




  return `/api/Auth/register`
}

export const postApiAuthRegister = async (registerDto?: RegisterDto, options?: RequestInit): Promise<postApiAuthRegisterResponse> => {

  const res = await fetch(getPostApiAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthRegisterResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiAuthRegisterResponse
}





export const getPostApiAuthRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data?: RegisterDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data?: RegisterDto}, TContext> => {

const mutationKey = ['postApiAuthRegister'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegister>>, {data?: RegisterDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRegister(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegister>>>
    export type PostApiAuthRegisterMutationBody = RegisterDto | undefined
    export type PostApiAuthRegisterMutationError = unknown

    export const usePostApiAuthRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data?: RegisterDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRegister>>,
        TError,
        {data?: RegisterDto},
        TContext
      > => {
      return useMutation(getPostApiAuthRegisterMutationOptions(options), queryClient);
    }

export type postApiAuthLoginResponse200 = {
  data: void
  status: 200
}

export type postApiAuthLoginResponseSuccess = (postApiAuthLoginResponse200) & {
  headers: Headers;
};
;

export type postApiAuthLoginResponse = (postApiAuthLoginResponseSuccess)

export const getPostApiAuthLoginUrl = () => {




  return `/api/Auth/login`
}

export const postApiAuthLogin = async (loginDto?: LoginDto, options?: RequestInit): Promise<postApiAuthLoginResponse> => {

  const res = await fetch(getPostApiAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthLoginResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiAuthLoginResponse
}





export const getPostApiAuthLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data?: LoginDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data?: LoginDto}, TContext> => {

const mutationKey = ['postApiAuthLogin'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, {data?: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthLogin(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = LoginDto | undefined
    export type PostApiAuthLoginMutationError = unknown

    export const usePostApiAuthLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data?: LoginDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        {data?: LoginDto},
        TContext
      > => {
      return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
    }

export type getApiListSharesResponse200 = {
  data: void
  status: 200
}

export type getApiListSharesResponseSuccess = (getApiListSharesResponse200) & {
  headers: Headers;
};
;

export type getApiListSharesResponse = (getApiListSharesResponseSuccess)

export const getGetApiListSharesUrl = () => {




  return `/api/ListShares`
}

export const getApiListShares = async ( options?: RequestInit): Promise<getApiListSharesResponse> => {

  const res = await fetch(getGetApiListSharesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiListSharesResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiListSharesResponse
}





export const getGetApiListSharesQueryKey = () => {
    return [
    `/api/ListShares`
    ] as const;
    }


export const getGetApiListSharesQueryOptions = <TData = Awaited<ReturnType<typeof getApiListShares>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListShares>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiListSharesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiListShares>>> = ({ signal }) => getApiListShares({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiListShares>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiListSharesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiListShares>>>
export type GetApiListSharesQueryError = unknown


export function useGetApiListShares<TData = Awaited<ReturnType<typeof getApiListShares>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListShares>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiListShares>>,
          TError,
          Awaited<ReturnType<typeof getApiListShares>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiListShares<TData = Awaited<ReturnType<typeof getApiListShares>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListShares>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiListShares>>,
          TError,
          Awaited<ReturnType<typeof getApiListShares>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiListShares<TData = Awaited<ReturnType<typeof getApiListShares>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListShares>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiListShares<TData = Awaited<ReturnType<typeof getApiListShares>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListShares>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiListSharesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type postApiListSharesResponse200 = {
  data: void
  status: 200
}

export type postApiListSharesResponseSuccess = (postApiListSharesResponse200) & {
  headers: Headers;
};
;

export type postApiListSharesResponse = (postApiListSharesResponseSuccess)

export const getPostApiListSharesUrl = () => {




  return `/api/ListShares`
}

export const postApiListShares = async (listShare?: ListShare, options?: RequestInit): Promise<postApiListSharesResponse> => {

  const res = await fetch(getPostApiListSharesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(listShare)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiListSharesResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiListSharesResponse
}





export const getPostApiListSharesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiListShares>>, TError,{data?: ListShare}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiListShares>>, TError,{data?: ListShare}, TContext> => {

const mutationKey = ['postApiListShares'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiListShares>>, {data?: ListShare}> = (props) => {
          const {data} = props ?? {};

          return  postApiListShares(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiListSharesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiListShares>>>
    export type PostApiListSharesMutationBody = ListShare | undefined
    export type PostApiListSharesMutationError = unknown

    export const usePostApiListShares = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiListShares>>, TError,{data?: ListShare}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiListShares>>,
        TError,
        {data?: ListShare},
        TContext
      > => {
      return useMutation(getPostApiListSharesMutationOptions(options), queryClient);
    }

export type putApiListSharesResponse200 = {
  data: void
  status: 200
}

export type putApiListSharesResponseSuccess = (putApiListSharesResponse200) & {
  headers: Headers;
};
;

export type putApiListSharesResponse = (putApiListSharesResponseSuccess)

export const getPutApiListSharesUrl = () => {




  return `/api/ListShares`
}

export const putApiListShares = async (listShare?: ListShare, options?: RequestInit): Promise<putApiListSharesResponse> => {

  const res = await fetch(getPutApiListSharesUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(listShare)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiListSharesResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiListSharesResponse
}





export const getPutApiListSharesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiListShares>>, TError,{data?: ListShare}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiListShares>>, TError,{data?: ListShare}, TContext> => {

const mutationKey = ['putApiListShares'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiListShares>>, {data?: ListShare}> = (props) => {
          const {data} = props ?? {};

          return  putApiListShares(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiListSharesMutationResult = NonNullable<Awaited<ReturnType<typeof putApiListShares>>>
    export type PutApiListSharesMutationBody = ListShare | undefined
    export type PutApiListSharesMutationError = unknown

    export const usePutApiListShares = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiListShares>>, TError,{data?: ListShare}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiListShares>>,
        TError,
        {data?: ListShare},
        TContext
      > => {
      return useMutation(getPutApiListSharesMutationOptions(options), queryClient);
    }

export type getApiListSharesIdResponse200 = {
  data: void
  status: 200
}

export type getApiListSharesIdResponseSuccess = (getApiListSharesIdResponse200) & {
  headers: Headers;
};
;

export type getApiListSharesIdResponse = (getApiListSharesIdResponseSuccess)

export const getGetApiListSharesIdUrl = (id: number,) => {




  return `/api/ListShares/${id}`
}

export const getApiListSharesId = async (id: number, options?: RequestInit): Promise<getApiListSharesIdResponse> => {

  const res = await fetch(getGetApiListSharesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiListSharesIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiListSharesIdResponse
}





export const getGetApiListSharesIdQueryKey = (id: number,) => {
    return [
    `/api/ListShares/${id}`
    ] as const;
    }


export const getGetApiListSharesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiListSharesId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListSharesId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiListSharesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiListSharesId>>> = ({ signal }) => getApiListSharesId(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiListSharesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiListSharesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiListSharesId>>>
export type GetApiListSharesIdQueryError = unknown


export function useGetApiListSharesId<TData = Awaited<ReturnType<typeof getApiListSharesId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListSharesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiListSharesId>>,
          TError,
          Awaited<ReturnType<typeof getApiListSharesId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiListSharesId<TData = Awaited<ReturnType<typeof getApiListSharesId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListSharesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiListSharesId>>,
          TError,
          Awaited<ReturnType<typeof getApiListSharesId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiListSharesId<TData = Awaited<ReturnType<typeof getApiListSharesId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListSharesId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiListSharesId<TData = Awaited<ReturnType<typeof getApiListSharesId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiListSharesId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiListSharesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type deleteApiListSharesIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiListSharesIdResponseSuccess = (deleteApiListSharesIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiListSharesIdResponse = (deleteApiListSharesIdResponseSuccess)

export const getDeleteApiListSharesIdUrl = (id: number,) => {




  return `/api/ListShares/${id}`
}

export const deleteApiListSharesId = async (id: number, options?: RequestInit): Promise<deleteApiListSharesIdResponse> => {

  const res = await fetch(getDeleteApiListSharesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiListSharesIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiListSharesIdResponse
}





export const getDeleteApiListSharesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiListSharesId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiListSharesId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiListSharesId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiListSharesId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiListSharesId(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiListSharesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiListSharesId>>>

    export type DeleteApiListSharesIdMutationError = unknown

    export const useDeleteApiListSharesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiListSharesId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiListSharesId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiListSharesIdMutationOptions(options), queryClient);
    }

export type getApiProductsResponse200 = {
  data: void
  status: 200
}

export type getApiProductsResponseSuccess = (getApiProductsResponse200) & {
  headers: Headers;
};
;

export type getApiProductsResponse = (getApiProductsResponseSuccess)

export const getGetApiProductsUrl = () => {




  return `/api/Products`
}

export const getApiProducts = async ( options?: RequestInit): Promise<getApiProductsResponse> => {

  const res = await fetch(getGetApiProductsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiProductsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiProductsResponse
}





export const getGetApiProductsQueryKey = () => {
    return [
    `/api/Products`
    ] as const;
    }


export const getGetApiProductsQueryOptions = <TData = Awaited<ReturnType<typeof getApiProducts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProducts>>> = ({ signal }) => getApiProducts({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProducts>>>
export type GetApiProductsQueryError = unknown


export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProducts>>,
          TError,
          Awaited<ReturnType<typeof getApiProducts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProducts>>,
          TError,
          Awaited<ReturnType<typeof getApiProducts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProducts<TData = Awaited<ReturnType<typeof getApiProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProducts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type postApiProductsResponse200 = {
  data: void
  status: 200
}

export type postApiProductsResponseSuccess = (postApiProductsResponse200) & {
  headers: Headers;
};
;

export type postApiProductsResponse = (postApiProductsResponseSuccess)

export const getPostApiProductsUrl = () => {




  return `/api/Products`
}

export const postApiProducts = async (product?: Product, options?: RequestInit): Promise<postApiProductsResponse> => {

  const res = await fetch(getPostApiProductsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(product)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiProductsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiProductsResponse
}





export const getPostApiProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProducts>>, TError,{data?: Product}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiProducts>>, TError,{data?: Product}, TContext> => {

const mutationKey = ['postApiProducts'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProducts>>, {data?: Product}> = (props) => {
          const {data} = props ?? {};

          return  postApiProducts(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProducts>>>
    export type PostApiProductsMutationBody = Product | undefined
    export type PostApiProductsMutationError = unknown

    export const usePostApiProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProducts>>, TError,{data?: Product}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiProducts>>,
        TError,
        {data?: Product},
        TContext
      > => {
      return useMutation(getPostApiProductsMutationOptions(options), queryClient);
    }

export type putApiProductsResponse200 = {
  data: void
  status: 200
}

export type putApiProductsResponseSuccess = (putApiProductsResponse200) & {
  headers: Headers;
};
;

export type putApiProductsResponse = (putApiProductsResponseSuccess)

export const getPutApiProductsUrl = () => {




  return `/api/Products`
}

export const putApiProducts = async (product?: Product, options?: RequestInit): Promise<putApiProductsResponse> => {

  const res = await fetch(getPutApiProductsUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(product)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiProductsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiProductsResponse
}





export const getPutApiProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiProducts>>, TError,{data?: Product}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiProducts>>, TError,{data?: Product}, TContext> => {

const mutationKey = ['putApiProducts'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiProducts>>, {data?: Product}> = (props) => {
          const {data} = props ?? {};

          return  putApiProducts(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiProductsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiProducts>>>
    export type PutApiProductsMutationBody = Product | undefined
    export type PutApiProductsMutationError = unknown

    export const usePutApiProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiProducts>>, TError,{data?: Product}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiProducts>>,
        TError,
        {data?: Product},
        TContext
      > => {
      return useMutation(getPutApiProductsMutationOptions(options), queryClient);
    }

export type getApiProductsIdResponse200 = {
  data: void
  status: 200
}

export type getApiProductsIdResponseSuccess = (getApiProductsIdResponse200) & {
  headers: Headers;
};
;

export type getApiProductsIdResponse = (getApiProductsIdResponseSuccess)

export const getGetApiProductsIdUrl = (id: number,) => {




  return `/api/Products/${id}`
}

export const getApiProductsId = async (id: number, options?: RequestInit): Promise<getApiProductsIdResponse> => {

  const res = await fetch(getGetApiProductsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiProductsIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiProductsIdResponse
}





export const getGetApiProductsIdQueryKey = (id: number,) => {
    return [
    `/api/Products/${id}`
    ] as const;
    }


export const getGetApiProductsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiProductsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProductsId>>> = ({ signal }) => getApiProductsId(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiProductsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProductsId>>>
export type GetApiProductsIdQueryError = unknown


export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProductsId>>,
          TError,
          Awaited<ReturnType<typeof getApiProductsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiProductsId<TData = Awaited<ReturnType<typeof getApiProductsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProductsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiProductsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type deleteApiProductsIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiProductsIdResponseSuccess = (deleteApiProductsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiProductsIdResponse = (deleteApiProductsIdResponseSuccess)

export const getDeleteApiProductsIdUrl = (id: number,) => {




  return `/api/Products/${id}`
}

export const deleteApiProductsId = async (id: number, options?: RequestInit): Promise<deleteApiProductsIdResponse> => {

  const res = await fetch(getDeleteApiProductsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiProductsIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiProductsIdResponse
}





export const getDeleteApiProductsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiProductsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiProductsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiProductsId(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiProductsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiProductsId>>>

    export type DeleteApiProductsIdMutationError = unknown

    export const useDeleteApiProductsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProductsId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiProductsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiProductsIdMutationOptions(options), queryClient);
    }

export type getApiShoppingListItemsResponse200 = {
  data: void
  status: 200
}

export type getApiShoppingListItemsResponseSuccess = (getApiShoppingListItemsResponse200) & {
  headers: Headers;
};
;

export type getApiShoppingListItemsResponse = (getApiShoppingListItemsResponseSuccess)

export const getGetApiShoppingListItemsUrl = () => {




  return `/api/ShoppingListItems`
}

export const getApiShoppingListItems = async ( options?: RequestInit): Promise<getApiShoppingListItemsResponse> => {

  const res = await fetch(getGetApiShoppingListItemsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiShoppingListItemsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiShoppingListItemsResponse
}





export const getGetApiShoppingListItemsQueryKey = () => {
    return [
    `/api/ShoppingListItems`
    ] as const;
    }


export const getGetApiShoppingListItemsQueryOptions = <TData = Awaited<ReturnType<typeof getApiShoppingListItems>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItems>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiShoppingListItemsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShoppingListItems>>> = ({ signal }) => getApiShoppingListItems({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiShoppingListItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiShoppingListItems>>>
export type GetApiShoppingListItemsQueryError = unknown


export function useGetApiShoppingListItems<TData = Awaited<ReturnType<typeof getApiShoppingListItems>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShoppingListItems>>,
          TError,
          Awaited<ReturnType<typeof getApiShoppingListItems>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShoppingListItems<TData = Awaited<ReturnType<typeof getApiShoppingListItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShoppingListItems>>,
          TError,
          Awaited<ReturnType<typeof getApiShoppingListItems>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShoppingListItems<TData = Awaited<ReturnType<typeof getApiShoppingListItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItems>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiShoppingListItems<TData = Awaited<ReturnType<typeof getApiShoppingListItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItems>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiShoppingListItemsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type postApiShoppingListItemsResponse200 = {
  data: void
  status: 200
}

export type postApiShoppingListItemsResponseSuccess = (postApiShoppingListItemsResponse200) & {
  headers: Headers;
};
;

export type postApiShoppingListItemsResponse = (postApiShoppingListItemsResponseSuccess)

export const getPostApiShoppingListItemsUrl = () => {




  return `/api/ShoppingListItems`
}

export const postApiShoppingListItems = async (shoppingListItem?: ShoppingListItem, options?: RequestInit): Promise<postApiShoppingListItemsResponse> => {

  const res = await fetch(getPostApiShoppingListItemsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(shoppingListItem)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiShoppingListItemsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiShoppingListItemsResponse
}





export const getPostApiShoppingListItemsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiShoppingListItems>>, TError,{data?: ShoppingListItem}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiShoppingListItems>>, TError,{data?: ShoppingListItem}, TContext> => {

const mutationKey = ['postApiShoppingListItems'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiShoppingListItems>>, {data?: ShoppingListItem}> = (props) => {
          const {data} = props ?? {};

          return  postApiShoppingListItems(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiShoppingListItemsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiShoppingListItems>>>
    export type PostApiShoppingListItemsMutationBody = ShoppingListItem | undefined
    export type PostApiShoppingListItemsMutationError = unknown

    export const usePostApiShoppingListItems = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiShoppingListItems>>, TError,{data?: ShoppingListItem}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiShoppingListItems>>,
        TError,
        {data?: ShoppingListItem},
        TContext
      > => {
      return useMutation(getPostApiShoppingListItemsMutationOptions(options), queryClient);
    }

export type putApiShoppingListItemsResponse200 = {
  data: void
  status: 200
}

export type putApiShoppingListItemsResponseSuccess = (putApiShoppingListItemsResponse200) & {
  headers: Headers;
};
;

export type putApiShoppingListItemsResponse = (putApiShoppingListItemsResponseSuccess)

export const getPutApiShoppingListItemsUrl = () => {




  return `/api/ShoppingListItems`
}

export const putApiShoppingListItems = async (shoppingListItem?: ShoppingListItem, options?: RequestInit): Promise<putApiShoppingListItemsResponse> => {

  const res = await fetch(getPutApiShoppingListItemsUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(shoppingListItem)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiShoppingListItemsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiShoppingListItemsResponse
}





export const getPutApiShoppingListItemsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiShoppingListItems>>, TError,{data?: ShoppingListItem}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiShoppingListItems>>, TError,{data?: ShoppingListItem}, TContext> => {

const mutationKey = ['putApiShoppingListItems'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiShoppingListItems>>, {data?: ShoppingListItem}> = (props) => {
          const {data} = props ?? {};

          return  putApiShoppingListItems(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiShoppingListItemsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiShoppingListItems>>>
    export type PutApiShoppingListItemsMutationBody = ShoppingListItem | undefined
    export type PutApiShoppingListItemsMutationError = unknown

    export const usePutApiShoppingListItems = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiShoppingListItems>>, TError,{data?: ShoppingListItem}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiShoppingListItems>>,
        TError,
        {data?: ShoppingListItem},
        TContext
      > => {
      return useMutation(getPutApiShoppingListItemsMutationOptions(options), queryClient);
    }

export type getApiShoppingListItemsIdResponse200 = {
  data: void
  status: 200
}

export type getApiShoppingListItemsIdResponseSuccess = (getApiShoppingListItemsIdResponse200) & {
  headers: Headers;
};
;

export type getApiShoppingListItemsIdResponse = (getApiShoppingListItemsIdResponseSuccess)

export const getGetApiShoppingListItemsIdUrl = (id: number,) => {




  return `/api/ShoppingListItems/${id}`
}

export const getApiShoppingListItemsId = async (id: number, options?: RequestInit): Promise<getApiShoppingListItemsIdResponse> => {

  const res = await fetch(getGetApiShoppingListItemsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiShoppingListItemsIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiShoppingListItemsIdResponse
}





export const getGetApiShoppingListItemsIdQueryKey = (id: number,) => {
    return [
    `/api/ShoppingListItems/${id}`
    ] as const;
    }


export const getGetApiShoppingListItemsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiShoppingListItemsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShoppingListItemsId>>> = ({ signal }) => getApiShoppingListItemsId(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiShoppingListItemsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiShoppingListItemsId>>>
export type GetApiShoppingListItemsIdQueryError = unknown


export function useGetApiShoppingListItemsId<TData = Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShoppingListItemsId>>,
          TError,
          Awaited<ReturnType<typeof getApiShoppingListItemsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShoppingListItemsId<TData = Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShoppingListItemsId>>,
          TError,
          Awaited<ReturnType<typeof getApiShoppingListItemsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShoppingListItemsId<TData = Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiShoppingListItemsId<TData = Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListItemsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiShoppingListItemsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type deleteApiShoppingListItemsIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiShoppingListItemsIdResponseSuccess = (deleteApiShoppingListItemsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiShoppingListItemsIdResponse = (deleteApiShoppingListItemsIdResponseSuccess)

export const getDeleteApiShoppingListItemsIdUrl = (id: number,) => {




  return `/api/ShoppingListItems/${id}`
}

export const deleteApiShoppingListItemsId = async (id: number, options?: RequestInit): Promise<deleteApiShoppingListItemsIdResponse> => {

  const res = await fetch(getDeleteApiShoppingListItemsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiShoppingListItemsIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiShoppingListItemsIdResponse
}





export const getDeleteApiShoppingListItemsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiShoppingListItemsId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiShoppingListItemsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiShoppingListItemsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiShoppingListItemsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiShoppingListItemsId(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiShoppingListItemsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiShoppingListItemsId>>>

    export type DeleteApiShoppingListItemsIdMutationError = unknown

    export const useDeleteApiShoppingListItemsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiShoppingListItemsId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiShoppingListItemsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiShoppingListItemsIdMutationOptions(options), queryClient);
    }

export type getApiShoppingListsResponse200 = {
  data: void
  status: 200
}

export type getApiShoppingListsResponseSuccess = (getApiShoppingListsResponse200) & {
  headers: Headers;
};
;

export type getApiShoppingListsResponse = (getApiShoppingListsResponseSuccess)

export const getGetApiShoppingListsUrl = () => {




  return `/api/ShoppingLists`
}

export const getApiShoppingLists = async ( options?: RequestInit): Promise<getApiShoppingListsResponse> => {

  const res = await fetch(getGetApiShoppingListsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiShoppingListsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiShoppingListsResponse
}





export const getGetApiShoppingListsQueryKey = () => {
    return [
    `/api/ShoppingLists`
    ] as const;
    }


export const getGetApiShoppingListsQueryOptions = <TData = Awaited<ReturnType<typeof getApiShoppingLists>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingLists>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiShoppingListsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShoppingLists>>> = ({ signal }) => getApiShoppingLists({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiShoppingListsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiShoppingLists>>>
export type GetApiShoppingListsQueryError = unknown


export function useGetApiShoppingLists<TData = Awaited<ReturnType<typeof getApiShoppingLists>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingLists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShoppingLists>>,
          TError,
          Awaited<ReturnType<typeof getApiShoppingLists>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShoppingLists<TData = Awaited<ReturnType<typeof getApiShoppingLists>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingLists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShoppingLists>>,
          TError,
          Awaited<ReturnType<typeof getApiShoppingLists>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShoppingLists<TData = Awaited<ReturnType<typeof getApiShoppingLists>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingLists>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiShoppingLists<TData = Awaited<ReturnType<typeof getApiShoppingLists>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingLists>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiShoppingListsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type postApiShoppingListsResponse200 = {
  data: void
  status: 200
}

export type postApiShoppingListsResponseSuccess = (postApiShoppingListsResponse200) & {
  headers: Headers;
};
;

export type postApiShoppingListsResponse = (postApiShoppingListsResponseSuccess)

export const getPostApiShoppingListsUrl = () => {




  return `/api/ShoppingLists`
}

export const postApiShoppingLists = async (shoppingList?: ShoppingList, options?: RequestInit): Promise<postApiShoppingListsResponse> => {

  const res = await fetch(getPostApiShoppingListsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(shoppingList)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiShoppingListsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiShoppingListsResponse
}





export const getPostApiShoppingListsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiShoppingLists>>, TError,{data?: ShoppingList}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiShoppingLists>>, TError,{data?: ShoppingList}, TContext> => {

const mutationKey = ['postApiShoppingLists'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiShoppingLists>>, {data?: ShoppingList}> = (props) => {
          const {data} = props ?? {};

          return  postApiShoppingLists(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiShoppingListsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiShoppingLists>>>
    export type PostApiShoppingListsMutationBody = ShoppingList | undefined
    export type PostApiShoppingListsMutationError = unknown

    export const usePostApiShoppingLists = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiShoppingLists>>, TError,{data?: ShoppingList}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiShoppingLists>>,
        TError,
        {data?: ShoppingList},
        TContext
      > => {
      return useMutation(getPostApiShoppingListsMutationOptions(options), queryClient);
    }

export type putApiShoppingListsResponse200 = {
  data: void
  status: 200
}

export type putApiShoppingListsResponseSuccess = (putApiShoppingListsResponse200) & {
  headers: Headers;
};
;

export type putApiShoppingListsResponse = (putApiShoppingListsResponseSuccess)

export const getPutApiShoppingListsUrl = () => {




  return `/api/ShoppingLists`
}

export const putApiShoppingLists = async (shoppingList?: ShoppingList, options?: RequestInit): Promise<putApiShoppingListsResponse> => {

  const res = await fetch(getPutApiShoppingListsUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(shoppingList)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiShoppingListsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiShoppingListsResponse
}





export const getPutApiShoppingListsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiShoppingLists>>, TError,{data?: ShoppingList}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiShoppingLists>>, TError,{data?: ShoppingList}, TContext> => {

const mutationKey = ['putApiShoppingLists'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiShoppingLists>>, {data?: ShoppingList}> = (props) => {
          const {data} = props ?? {};

          return  putApiShoppingLists(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiShoppingListsMutationResult = NonNullable<Awaited<ReturnType<typeof putApiShoppingLists>>>
    export type PutApiShoppingListsMutationBody = ShoppingList | undefined
    export type PutApiShoppingListsMutationError = unknown

    export const usePutApiShoppingLists = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiShoppingLists>>, TError,{data?: ShoppingList}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiShoppingLists>>,
        TError,
        {data?: ShoppingList},
        TContext
      > => {
      return useMutation(getPutApiShoppingListsMutationOptions(options), queryClient);
    }

export type getApiShoppingListsIdResponse200 = {
  data: void
  status: 200
}

export type getApiShoppingListsIdResponseSuccess = (getApiShoppingListsIdResponse200) & {
  headers: Headers;
};
;

export type getApiShoppingListsIdResponse = (getApiShoppingListsIdResponseSuccess)

export const getGetApiShoppingListsIdUrl = (id: number,) => {




  return `/api/ShoppingLists/${id}`
}

export const getApiShoppingListsId = async (id: number, options?: RequestInit): Promise<getApiShoppingListsIdResponse> => {

  const res = await fetch(getGetApiShoppingListsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiShoppingListsIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiShoppingListsIdResponse
}





export const getGetApiShoppingListsIdQueryKey = (id: number,) => {
    return [
    `/api/ShoppingLists/${id}`
    ] as const;
    }


export const getGetApiShoppingListsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiShoppingListsId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListsId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiShoppingListsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShoppingListsId>>> = ({ signal }) => getApiShoppingListsId(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiShoppingListsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiShoppingListsId>>>
export type GetApiShoppingListsIdQueryError = unknown


export function useGetApiShoppingListsId<TData = Awaited<ReturnType<typeof getApiShoppingListsId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShoppingListsId>>,
          TError,
          Awaited<ReturnType<typeof getApiShoppingListsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShoppingListsId<TData = Awaited<ReturnType<typeof getApiShoppingListsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShoppingListsId>>,
          TError,
          Awaited<ReturnType<typeof getApiShoppingListsId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiShoppingListsId<TData = Awaited<ReturnType<typeof getApiShoppingListsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiShoppingListsId<TData = Awaited<ReturnType<typeof getApiShoppingListsId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiShoppingListsId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiShoppingListsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type deleteApiShoppingListsIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiShoppingListsIdResponseSuccess = (deleteApiShoppingListsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiShoppingListsIdResponse = (deleteApiShoppingListsIdResponseSuccess)

export const getDeleteApiShoppingListsIdUrl = (id: number,) => {




  return `/api/ShoppingLists/${id}`
}

export const deleteApiShoppingListsId = async (id: number, options?: RequestInit): Promise<deleteApiShoppingListsIdResponse> => {

  const res = await fetch(getDeleteApiShoppingListsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiShoppingListsIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiShoppingListsIdResponse
}





export const getDeleteApiShoppingListsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiShoppingListsId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiShoppingListsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiShoppingListsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiShoppingListsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiShoppingListsId(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiShoppingListsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiShoppingListsId>>>

    export type DeleteApiShoppingListsIdMutationError = unknown

    export const useDeleteApiShoppingListsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiShoppingListsId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiShoppingListsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiShoppingListsIdMutationOptions(options), queryClient);
    }

export type getApiUsersResponse200 = {
  data: void
  status: 200
}

export type getApiUsersResponseSuccess = (getApiUsersResponse200) & {
  headers: Headers;
};
;

export type getApiUsersResponse = (getApiUsersResponseSuccess)

export const getGetApiUsersUrl = () => {




  return `/api/Users`
}

export const getApiUsers = async ( options?: RequestInit): Promise<getApiUsersResponse> => {

  const res = await fetch(getGetApiUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiUsersResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiUsersResponse
}





export const getGetApiUsersQueryKey = () => {
    return [
    `/api/Users`
    ] as const;
    }


export const getGetApiUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({ signal }) => getApiUsers({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsers>>>
export type GetApiUsersQueryError = unknown


export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type postApiUsersResponse200 = {
  data: void
  status: 200
}

export type postApiUsersResponseSuccess = (postApiUsersResponse200) & {
  headers: Headers;
};
;

export type postApiUsersResponse = (postApiUsersResponseSuccess)

export const getPostApiUsersUrl = () => {




  return `/api/Users`
}

export const postApiUsers = async (user?: User, options?: RequestInit): Promise<postApiUsersResponse> => {

  const res = await fetch(getPostApiUsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(user)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiUsersResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiUsersResponse
}





export const getPostApiUsersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsers>>, TError,{data?: User}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsers>>, TError,{data?: User}, TContext> => {

const mutationKey = ['postApiUsers'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsers>>, {data?: User}> = (props) => {
          const {data} = props ?? {};

          return  postApiUsers(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsers>>>
    export type PostApiUsersMutationBody = User | undefined
    export type PostApiUsersMutationError = unknown

    export const usePostApiUsers = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsers>>, TError,{data?: User}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsers>>,
        TError,
        {data?: User},
        TContext
      > => {
      return useMutation(getPostApiUsersMutationOptions(options), queryClient);
    }

export type putApiUsersResponse200 = {
  data: void
  status: 200
}

export type putApiUsersResponseSuccess = (putApiUsersResponse200) & {
  headers: Headers;
};
;

export type putApiUsersResponse = (putApiUsersResponseSuccess)

export const getPutApiUsersUrl = () => {




  return `/api/Users`
}

export const putApiUsers = async (user?: User, options?: RequestInit): Promise<putApiUsersResponse> => {

  const res = await fetch(getPutApiUsersUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(user)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiUsersResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiUsersResponse
}





export const getPutApiUsersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiUsers>>, TError,{data?: User}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiUsers>>, TError,{data?: User}, TContext> => {

const mutationKey = ['putApiUsers'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiUsers>>, {data?: User}> = (props) => {
          const {data} = props ?? {};

          return  putApiUsers(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiUsersMutationResult = NonNullable<Awaited<ReturnType<typeof putApiUsers>>>
    export type PutApiUsersMutationBody = User | undefined
    export type PutApiUsersMutationError = unknown

    export const usePutApiUsers = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiUsers>>, TError,{data?: User}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiUsers>>,
        TError,
        {data?: User},
        TContext
      > => {
      return useMutation(getPutApiUsersMutationOptions(options), queryClient);
    }

export type getApiUsersIdResponse200 = {
  data: void
  status: 200
}

export type getApiUsersIdResponseSuccess = (getApiUsersIdResponse200) & {
  headers: Headers;
};
;

export type getApiUsersIdResponse = (getApiUsersIdResponseSuccess)

export const getGetApiUsersIdUrl = (id: number,) => {




  return `/api/Users/${id}`
}

export const getApiUsersId = async (id: number, options?: RequestInit): Promise<getApiUsersIdResponse> => {

  const res = await fetch(getGetApiUsersIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiUsersIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiUsersIdResponse
}





export const getGetApiUsersIdQueryKey = (id: number,) => {
    return [
    `/api/Users/${id}`
    ] as const;
    }


export const getGetApiUsersIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsersId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersId>>> = ({ signal }) => getApiUsersId(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsersId>>>
export type GetApiUsersIdQueryError = unknown


export function useGetApiUsersId<TData = Awaited<ReturnType<typeof getApiUsersId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersId>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersId<TData = Awaited<ReturnType<typeof getApiUsersId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersId>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersId<TData = Awaited<ReturnType<typeof getApiUsersId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUsersId<TData = Awaited<ReturnType<typeof getApiUsersId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUsersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type deleteApiUsersIdResponse200 = {
  data: void
  status: 200
}

export type deleteApiUsersIdResponseSuccess = (deleteApiUsersIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiUsersIdResponse = (deleteApiUsersIdResponseSuccess)

export const getDeleteApiUsersIdUrl = (id: number,) => {




  return `/api/Users/${id}`
}

export const deleteApiUsersId = async (id: number, options?: RequestInit): Promise<deleteApiUsersIdResponse> => {

  const res = await fetch(getDeleteApiUsersIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiUsersIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiUsersIdResponse
}





export const getDeleteApiUsersIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiUsersId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiUsersId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiUsersId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiUsersId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiUsersId(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiUsersId>>>

    export type DeleteApiUsersIdMutationError = unknown

    export const useDeleteApiUsersId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiUsersId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiUsersId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiUsersIdMutationOptions(options), queryClient);
    }

